<template>
    <div class="box">
        <div class="columns">
            <div class="column">
                <i>{{createdOn}}</i>
                <h4 class="title is-4">
                    <router-link :to="'/listing/' + listing._linkedid">{{listing.title}}</router-link>
                    <span class="tag is-dark is-medium listing-budget-tag">{{listing.price.amount}} {{listing.price.currency.toUpperCase()}}</span>
                </h4>
                <p>
                    <text-summary :text="listing.description" />
                </p>

                <div class="tags are-medium">
                    <span class="tag" v-for="tag in listing.tags" :key="tag">{{tag}}</span>

                </div>
            </div>

            <div class="column is-2">

                <div class="box listing-user-box">
                    <img class="listing-user-avatar"  src='https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortRound&accessoriesType=Blank&hairColor=Red&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Yellow'
                    />
                    <br/>
                    <div class="listing-user-name">{{user && `${user.firstName} ${user.lastName}` || "Unknown"}}</div>

                    <div class="tags has-addons">
                        <span class="tag">Rating</span>
                        <span class="tag is-primary" :class="rating==-1 ? 'button is-loading': ''">{{rating}}%</span>
                    </div>
                </div>

                <!--                                    <button class="button is-primary is-large is-fullwidth font-circular">View</button>-->
            </div>
        </div>
        <nav class="level is-mobile">
            <div class="level-left">
                <a class="level-item" aria-label="reply">
                    <b-icon pack="fas" icon="reply"></b-icon>
                    <span class="icon-label">Message</span>
                </a>
                <a class="level-item" aria-label="retweet">
                    <b-icon pack="fas" icon="retweet"></b-icon>
                    <span class="icon-label">Share</span>
                </a>
                <a class="level-item" aria-label="like" @click="saveBtnClicked=!saveBtnClicked">
                    <b-icon pack="fas" icon="heart" :class="saveBtnClicked ? 'scale-up-center' : 'scale-down-center'"></b-icon>
                    <span class="icon-label">
                        {{saveBtnClicked ? "Unsave" : "Save"}}
<!--                        <div class="text-transition" :class="!saveBtnClicked && 'text-hidden'">Unsave</div>-->
<!--                        <div class="text-transition" :class="saveBtnClicked && 'text-hidden'">Save</div>-->
                    </span>
                </a>
            </div>

            <div class="level-right">
                <a class="level-item report-btn" aria-label="retweet">
                    <b-icon pack="fas" icon="exclamation-circle"></b-icon>
                    <span class="icon-label">Report</span>
                </a>
            </div>
        </nav>
    </div>
</template>

<script>
    import TextSummary from "../text/TextSummary";
    import moment from 'moment';
    const fb = require('../../../plugins/firebase');

    export default {
        name: "ListingBox",
        components: {
            TextSummary
        },
        props: {
            listing: Object,
        },
        data() {
            return {
                user: null,
                saveBtnClicked: false
            }
        },
        mounted() {
            this.loadUser();
        },
        computed: {
            createdOn() {
                return moment(this.listing.created_on.toDate()).fromNow();
            },
            rating() {
                if (!this.user) return -1;
                const {total, positive, negative} = this.user.rating;
                const neutral = total - positive - negative;
                const weightedScore = positive + neutral*0.5;
                return ((weightedScore/total)*100).toFixed(0);
            }
        },
        methods: {
            async loadUser() {
                const uid = this.listing.user_id;
                if (uid) {
                    let snap = await fb.usersCollection.doc(uid).get();
                    if (snap.exists) {
                        this.user = snap.data();
                    }
                }
            }
        }
    }
</script>

<style scoped>
    /* ----------------------------------------------
     * Generated by Animista on 2020-6-8 21:26:38
     * Licensed under FreeBSD License.
     * See http://animista.net/license for more info.
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation scale-up-center
     * ----------------------------------------
     */
    @-webkit-keyframes scale-up-center {
        0% {
            -webkit-transform: scale(0.5);
            transform: scale(0.5);
        }
        70% {
            -webkit-transform: scale(1.2);
            transform: scale(1.2);
        }
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
    }
    @keyframes scale-up-center {
        0% {
            -webkit-transform: scale(0.5);
            transform: scale(0.5);
        }
        70% {
            -webkit-transform: scale(1.2);
            transform: scale(1.2);
        }
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
    }

    /**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
    @-webkit-keyframes scale-down-center {
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
        95% {
            -webkit-transform: scale(0);
            transform: scale(0);
        }
        0% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
    }
    @keyframes scale-down-center {
        100% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
        95% {
            -webkit-transform: scale(0);
            transform: scale(0);
        }
        0% {
            -webkit-transform: scale(1);
            transform: scale(1);
        }
    }


    .scale-up-center {
        -webkit-animation: scale-up-center 0.3s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        animation: scale-up-center 0.3s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    }

    .scale-down-center {
        -webkit-animation: scale-down-center 0.15s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
        animation: scale-down-center 0.15s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    }

    /*.text-transition {*/
    /*    transition: opacity 0.5s linear;*/
    /*}*/

    /*.text-hidden {*/
    /*    opacity: 0;*/
    /*    width: 0px;*/
    /*}*/
</style>